---
galaxy_info:
  role_name: web
  author: CIA Team
  description: Nginx web server - internal website
  license: MIT
  min_ansible_version: "2.16"
  platforms:
    - name: Ubuntu
      versions:
        - noble
dependencies:
  - role: common
allow_duplicates: false
